### ISSUE TITLE
Implementation with i18n

### ISSUE THREAD

**Issue by nagman** [glemiere/nextjs-starter#1]
Hi!
Great starter! A friend from 42 gave me the link recently :)
It saved me a lot of time setting up my project!

But I struggle with implementing a translation package with next.
No matter what I try, impossible to make it work with the starter.
I tried [this](https://react.i18next.com/), [this](https://github.com/zeit/next.js/tree/canary/examples/with-react-i18next) and [this](https://github.com/zeit/next.js/tree/canary/examples/with-react-intl).

It's my first next project, also, so I may have made mistakes. I've noticed that next can be implemented with different manners (some use _document.jsx, some don't, for instance).

Do you have a clue? Do you need code samples to understand my struggle?

PS : je me permets de parler anglais au cas où nos amis bouffeurs de gelée auraient le même problème ;)

**Comment by glemiere** [comment]
Hi @nagman, happy to see an alumni here! Thanks, I'm glad you appreciate this project.

Well the easiest way to implement an internationalization in my opinion, would be for you to create a module exporting an array of objects with string keys such as "en" or "fr" representing the language. Then each object would contain a set of key/value pair that you can reuse in your entire app.
Finally : you could use the user agent to detect the user language and apply the right one accordingly.

In practice, it would look like this : `i18n.js `
```
module.exports = [
  "en" : {
    "hello": "Heeey there!"
    ...
  },
  "fr" : {
    "hello": "Bonjour les amis!"
    ...
  }
][window.navigator.language.substring(0, window.navigator.language.indexOf('-'))]
```

Then you could just import it wherever you want.
`import language from 'i18n.js'`

And then use it like
`<h1>{language.hello}</h1>`

And voila!
Let me know what you think ;)

**Comment by glemiere** [comment]
You can follow the next part of this issue right there : https://github.com/glemiere/nextjs-starter/issues/2

**Comment by nagman** [comment]
Wow! Top merci!
I'll give it a try and come back to you :)

Also, for the css handling, I may have a solution (not perfect but it uses SASS modules and it works extremely well). I just need to make it work with postcss-autoprefix and I'll make a pull request in order to replace this style tag stuff (which is I agree very ugly).
